# Generated by Django 5.0.3 on 2024-04-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografria',
            new_name='Fotografia',
        ),
    ]
